apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multicontainer
  name: multicontainer
spec:
  containers:
  - image: busybox
    name: multicontainer
    command:
      - sleep
      - "3600"  
  - image: nginx
    name: nginx
